AWSTemplateFormatVersion: "2010-09-09"
Description: Serverless Scheduler without cluster state
Resources:
  QueueScheduling:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-scheduling
  DynamoNodes:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-nodes
      GlobalSecondaryIndexes:
        - IndexName: ttl_idx
          KeySchema:
            - AttributeName: part
              KeyType: HASH
            - AttributeName: ttl
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: cap_idx
          KeySchema:
            - AttributeName: pool
              KeyType: HASH
            - AttributeName: cap
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: part
          AttributeType: N
        - AttributeName: ttl
          AttributeType: N
        - AttributeName: cap
          AttributeType: N
        - AttributeName: pool
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
  DynamoClaims:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-claims
      GlobalSecondaryIndexes:
        - IndexName: ttl_idx
          KeySchema:
            - AttributeName: part
              KeyType: HASH
            - AttributeName: ttl
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: node_idx
          KeySchema:
            - AttributeName: node
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: node
          AttributeType: S
        - AttributeName: part
          AttributeType: N
        - AttributeName: ttl
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
