AWSTemplateFormatVersion: "2010-09-09"
Description: Serverless Scheduler without cluster state
Resources:
  DynamoPhishes:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-nodes
      GlobalSecondaryIndexes:
        - IndexName: ttl_idx
          KeySchema:
            - AttributeName: ttl
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: cap_idx
          KeySchema:
            - AttributeName: pool
              KeyType: HASH
            - AttributeName: cap
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: ttl
          AttributeType: N
        - AttributeName: cap
          AttributeType: N
        - AttributeName: pool
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
